#ifndef GPU
#define GPU
#define DEFAULT_THREADS_PER_BLOCK 256
#define DEFAULT_MAX_BLOCKS_PER_GRID 4096

// blockDim
//#define DEFAULT_THREADS_PER_BLOCK 8
// gridDim
//#define DEFAULT_MAX_BLOCKS_PER_GRID 128
#endif